version: '3'
services:
  api:
    container_name: repositorie-filter-api
    image: node:16
    working_dir: /usr/api/repositories-filter-api
    restart: unless-stopped
    command: bash -c "npm install && npm run dev"
    volumes:
      - .:/usr/api/repositories-filter-api
    ports:
      - '3000:${PORT}'
